
import type { Metadata } from "next";
import { Inter as FontSans} from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/providers/UserContext";

const fontSans = FontSans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="pt-BR">
      <body
        className={`${fontSans.variable} min-h-screen font-sans antialiased dark`}
      > 
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
